[package]
name = "id-generator"
version = "1.0.0"
authors = ["Edwin Sundberg <edwin@edthing.com>"]
edition = "2021"

[dependencies]
actix-web = "4.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
prometheus = "0.13"
lazy_static = "1.4"
